#BeKit
#BEKIT    ——By Lavainmc (Lava不是岩浆)
#bekit
# 在进入下列世界时给予套装
givable-worlds:
  - "example"

# 是否启用箱子菜单
chest-menu: true

# 消息设置
msg-no-permission: "§bBeKit§7>> §c你没有权限执行此命令!"
msg-save-success: "§bBeKit§7>> §a套件保存成功!"
msg-save-fail: "§bBeKit§7>> §c套件保存失败!"
msg-delete-success: "§bBeKit§7>> §a套件删除成功!"
msg-delete-fail: "§bBeKit§7>> §c套件删除失败!"

#Do not change this!!!
#不要修改这个!!!
config-version: "1.0"